-- =============================================================================
-- Admin users (Supabase Auth + public.app_admins)
-- =============================================================================
--
-- Do NOT insert into auth.users via SQL — sign-in often returns HTTP 500 because
-- GoTrue expects its own password hashes.
--
-- Recommended: from frontend/
--   npm run create-admins
--
-- This creates (defaults):
--   • nirruu20@bm-portfolio.org / 200605     → app_admins.role = 'super'   (full admin)
--   • bmahalakshmi@bm-portfolio.org / bmahalakshmi → role = 'editor' (Teaching only in app)
--
-- Requires: VITE_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY in frontend/.env
-- Database: run docs/sql/005_app_admins_role.sql once if app_admins has no "role" column.
--
-- Sign in at /admin/login with username + password (no @ required):
--   nirruu20  /  200605
--   bmahalakshmi  /  bmahalakshmi
-- Or full email: nirruu20@bm-portfolio.org, bmahalakshmi@bm-portfolio.org
--
-- Manual registration (after Dashboard → Authentication → Add user):
--   INSERT INTO public.app_admins (user_id, role)
--   SELECT id, 'super'::text
--   FROM auth.users WHERE lower(email) = lower('you@example.com') LIMIT 1
--   ON CONFLICT (user_id) DO UPDATE SET role = EXCLUDED.role;
--
-- =============================================================================
